
title: 甲与
email: 
description: 用来记录一些编程经验
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tufafo.github.io"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

minimal_mistakes_skin: "neon"
locale: "zh-CN"
name: 甲与

# teaser: /assets/images/甲与.png
logo: /assets/images/6.png
# breadcrumbs: true



#author: Jiayu

author:
  name: "甲与"
  avatar: "/assets/images/6.png"
  bio: "记录"
  



tag_archive:
  type: liquid
  path: /tags/

defaults:
  #_posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      author_profile: true
      toc: true
      toc_label: "目录"

words_per_minute: 200
search: true



lunr:
  search_within_pages: true # 50words

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
